"""Compile a semantic ``RecipeConfig`` into diffusion-pipe TOML configs.

diffusion-pipe is config-driven instead of CLI-flag-driven: ``train.py`` takes
a single ``--config`` pointing at a TOML file, and that TOML in turn points at
a dataset TOML. This module produces both files (purely as strings + paths)
so the launcher can write them to disk and shell out.

The compiler is deliberately a pure function: callers pass in the recipe and
a workspace directory, and get back ``(argv, files_to_write)`` where
``argv`` is what to append after ``train.py`` and ``files_to_write`` maps
absolute paths to file contents. No disk I/O here keeps the unit tests fast.

Reference shape: see ``diffusion-pipe/examples/main_example.toml`` and
``diffusion-pipe/examples/dataset.toml`` in the upstream repo.
"""

from __future__ import annotations

from pathlib import Path

from lorahub.core.config.schema import RecipeConfig

__all__ = ["CompilationError", "compile_recipe"]


class CompilationError(ValueError):
    """Raised when a recipe cannot be expressed in diffusion-pipe's vocabulary."""


# diffusion-pipe currently supports SDXL, Flux, and SD3 from our registered
# arch list. SD1.5 is intentionally absent from upstream's supported_models.md.
_SUPPORTED_ARCHS: frozenset[str] = frozenset({"sdxl", "flux", "sd3"})

# Map our optimizer.type values onto names diffusion-pipe accepts directly.
# Anything not in this map is passed through verbatim and resolved by
# diffusion-pipe via pytorch_optimizer (which is its escape hatch).
_OPTIMIZER_MAP: dict[str, str] = {
    "adamw": "adamw",
    "adamw8bit": "adamw8bit",
    "adamw_optimi": "adamw_optimi",
    "adamw8bitkahan": "AdamW8bitKahan",
    "lion": "Lion",
    "lion8bit": "Lion8bit",
    "prodigy": "Prodigy",
    "automagic": "automagic",
}

# Recipe scheduler -> diffusion-pipe scheduler. dp only ships constant /
# linear / cosine; anything implying restarts collapses to plain cosine.
_SCHEDULER_MAP: dict[str, str] = {
    "constant": "constant",
    "linear": "linear",
    "cosine": "cosine",
    "cosine_with_restarts": "cosine",
}


def compile_recipe(
    recipe: RecipeConfig,
    workspace: Path,
) -> tuple[list[str], dict[Path, str]]:
    """Translate a recipe into ``(argv, files_to_write)`` for diffusion-pipe.

    ``argv`` is what to append after ``python train.py`` -- typically
    ``["--deepspeed", "--config", "<workspace>/diffusion_pipe.toml"]``.
    ``files_to_write`` is a mapping of absolute path to file contents the
    launcher must write before spawning the process.
    """
    arch = recipe.base_model.arch
    if arch not in _SUPPORTED_ARCHS:
        msg = (
            f"diffusion-pipe does not support arch {arch!r}; "
            f"supported: {sorted(_SUPPORTED_ARCHS)}. Use the kohya backend instead."
        )
        raise CompilationError(msg)

    workspace = workspace.resolve()
    config_path = workspace / "diffusion_pipe.toml"
    dataset_path = workspace / "dataset.toml"

    files: dict[Path, str] = {
        dataset_path: _build_dataset_toml(recipe),
        config_path: _build_main_toml(recipe, workspace, dataset_path),
    }
    argv = ["--deepspeed", "--config", str(config_path)]
    return argv, files


# --------------------------------------------------------------------------- #
# Main config TOML
# --------------------------------------------------------------------------- #


def _build_main_toml(recipe: RecipeConfig, workspace: Path, dataset_path: Path) -> str:
    out_dir = recipe.output.output_dir or (workspace / "output")
    parts: list[str] = [
        "# Auto-generated by lorahub. Do not edit by hand.",
        f"output_dir = {_toml_str(str(out_dir))}",
        f"dataset = {_toml_str(str(dataset_path))}",
        "",
        f"epochs = {recipe.schedule.epochs}",
        f"micro_batch_size_per_gpu = {recipe.schedule.batch_size}",
        f"gradient_accumulation_steps = {recipe.schedule.grad_accum}",
        "pipeline_stages = 1",
        "gradient_clipping = 1.0",
        f"warmup_steps = {recipe.optimizer.warmup_steps}",
    ]
    scheduler = _scheduler_for(recipe.optimizer.schedule)
    if scheduler != "constant":
        parts.append(f"lr_scheduler = {_toml_str(scheduler)}")
    if recipe.schedule.max_steps is not None:
        parts.append(f"max_steps = {recipe.schedule.max_steps}")

    parts += [
        "",
        f"save_every_n_epochs = {recipe.output.save_every_n_epochs}",
        f"activation_checkpointing = {_toml_bool(recipe.gradient_checkpointing)}",
        "partition_method = 'parameters'",
        f"save_dtype = {_toml_str(_save_dtype(recipe.output.save_dtype))}",
        "caching_batch_size = 1",
        "steps_per_print = 1",
        "",
    ]

    parts += _model_section(recipe)
    parts += [""]
    parts += _adapter_section(recipe)
    parts += [""]
    parts += _optimizer_section(recipe)
    parts += [""]
    parts += [
        "[monitoring]",
        "enable_wandb = false",
        "",
    ]
    return "\n".join(parts)


def _model_section(recipe: RecipeConfig) -> list[str]:
    arch = recipe.base_model.arch
    dtype = "bfloat16" if recipe.precision in ("bf16", "fp32") else "float16"
    lines: list[str] = ["[model]", f"type = {_toml_str(arch)}"]

    if arch == "sdxl":
        lines.append(f"checkpoint_path = {_toml_str(str(recipe.base_model.checkpoint))}")
    else:
        # Flux and SD3 expect a Diffusers folder.
        lines.append(f"diffusers_path = {_toml_str(str(recipe.base_model.checkpoint))}")

    lines.append(f"dtype = {_toml_str(dtype)}")
    return lines


def _adapter_section(recipe: RecipeConfig) -> list[str]:
    n = recipe.network
    if n.type != "lora":
        # diffusion-pipe upstream only ships a `lora` adapter type today.
        # Surface that early instead of letting train.py crash with
        # `Adapter type {x} is not implemented`.
        msg = (
            f"diffusion-pipe only supports network.type='lora'; got {n.type!r}. "
            "Use the kohya backend for locon/loha/dora."
        )
        raise CompilationError(msg)

    # diffusion-pipe forces alpha = rank (see train.py:118-122). It will
    # reject the toml if `alpha` is set explicitly, so we omit the field.
    return [
        "[adapter]",
        "type = 'lora'",
        f"rank = {n.rank}",
    ]


def _optimizer_section(recipe: RecipeConfig) -> list[str]:
    o = recipe.optimizer
    opt_type = _OPTIMIZER_MAP.get(o.type.lower(), o.type)
    parts = [
        "[optimizer]",
        f"type = {_toml_str(opt_type)}",
        f"lr = {o.lr.unet}",
        f"betas = [{o.betas[0]}, {o.betas[1]}]",
        f"weight_decay = {o.weight_decay}",
        f"eps = {o.eps}",
    ]
    # Free-form optimizer_args -> toml lines. Keys win over the dedicated
    # fields when names collide (matches the kohya backend's behaviour).
    seen = {"type", "lr", "betas", "weight_decay", "eps"}
    for key, value in o.optimizer_args.items():
        if key in seen:
            # Replace the prior entry instead of appending a duplicate.
            parts = [p for p in parts if not p.startswith(f"{key} =")]
        parts.append(f"{key} = {_toml_str(value)}")
    return parts


def _scheduler_for(name: str) -> str:
    return _SCHEDULER_MAP.get(name, "constant")


def _save_dtype(name: str) -> str:
    if name == "fp16":
        return "float16"
    if name == "bf16":
        return "bfloat16"
    return "float32"


# --------------------------------------------------------------------------- #
# Dataset TOML
# --------------------------------------------------------------------------- #


def _build_dataset_toml(recipe: RecipeConfig) -> str:
    ds = recipe.dataset
    if len(ds.resolution) == 1:
        resolutions = f"[{ds.resolution[0]}]"
    else:
        # diffusion-pipe accepts (width, height) pairs as nested arrays.
        resolutions = f"[[{ds.resolution[0]}, {ds.resolution[1]}]]"

    parts: list[str] = [
        "# Auto-generated by lorahub. Do not edit by hand.",
        f"resolutions = {resolutions}",
        f"enable_ar_bucket = {_toml_bool(ds.bucket.enabled)}",
    ]
    if ds.bucket.enabled:
        parts += [
            "min_ar = 0.5",
            "max_ar = 2.0",
            "num_ar_buckets = 7",
        ]
    # `frame_buckets = [1]` keeps the dataset image-only; it's safe for
    # every image arch the schema currently ships (sdxl, flux, sd3).
    parts += [
        "frame_buckets = [1]",
        "",
        "[[directory]]",
        f"path = {_toml_str(str(ds.source))}",
        f"num_repeats = {ds.num_repeats}",
        "",
    ]
    return "\n".join(parts)


# --------------------------------------------------------------------------- #
# TOML literal helpers
# --------------------------------------------------------------------------- #


def _toml_str(value: str) -> str:
    """Emit a TOML basic string literal (escaped) for ``value``."""
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _toml_bool(value: bool) -> str:
    return "true" if value else "false"
