"""KohyaBackend: implements `TrainingBackend` by wrapping kohya_ss/sd-scripts."""

from __future__ import annotations

import os
import shutil
from collections.abc import Callable
from pathlib import Path

import ulid

from lorahub.core.backends._common.vram import estimate_vram as _shared_estimate_vram
from lorahub.core.backends.base import (
    ModelArch,
    Severity,
    TrainingHandle,
    ValidationIssue,
    VRAMEstimate,
)
from lorahub.core.backends.kohya import _attn_patch
from lorahub.core.backends.kohya import bootstrap as _bootstrap
from lorahub.core.backends.kohya.compiler import (
    CompilationError,
    _KOHYA_SCRIPT_MAP,
    compile_config,
)
from lorahub.core.backends.kohya.runner import KohyaRunner
from lorahub.core.config.schema import TrainingConfig
from lorahub.core.events import TrainingEvent

# kohya sd-scripts ships dedicated entry points for these arches today
# (see compiler._KOHYA_SCRIPT_MAP). diffusion-pipe-only entries (Wan,
# HunyuanVideo, Cosmos, Chroma, ...) are intentionally excluded.
_SUPPORTED: set[ModelArch] = {ModelArch(arch) for arch in _KOHYA_SCRIPT_MAP}


# sitecustomize template that loads the FA3/FA4 dispatcher shim. We copy
# `_attn_patch.py` next to it so the spawned interpreter doesn't depend on
# our package being importable from its venv.
_SITECUSTOMIZE_TEMPLATE = """\
# Auto-generated by LoraHub. Loaded automatically because PYTHONPATH points
# at this directory. Forwards to the FA3/FA4 monkey-patch in _attn_patch.py.
try:
    import _attn_patch  # type: ignore[import-not-found]
    _attn_patch.apply()
except Exception:
    # Never let a misbehaving patch crash the host trainer; the worst case
    # is the user keeps their FA2 path which is already kohya's default.
    import logging
    logging.getLogger(__name__).exception("LoraHub attn patch failed to load")
"""


def _stage_attn_patch(workspace: Path) -> Path:
    """Write sitecustomize.py + a copy of _attn_patch under the workspace.

    Returns the directory the caller should prepend to ``PYTHONPATH`` so
    the spawned Python picks up the sitecustomize hook automatically.
    Idempotent — repeat calls overwrite the staged files.
    """
    shim_dir = workspace / "_lorahub_attn"
    shim_dir.mkdir(parents=True, exist_ok=True)
    (shim_dir / "sitecustomize.py").write_text(
        _SITECUSTOMIZE_TEMPLATE,
        encoding="utf-8",
    )
    src = Path(_attn_patch.__file__).resolve()
    shutil.copyfile(src, shim_dir / "_attn_patch.py")
    return shim_dir


class KohyaBackend:
    """Wraps kohya_ss/sd-scripts as a TrainingBackend."""

    @property
    def name(self) -> str:
        return "kohya"

    @property
    def supported_archs(self) -> set[ModelArch]:
        return set(_SUPPORTED)

    def validate(self, cfg: TrainingConfig) -> list[ValidationIssue]:
        issues: list[ValidationIssue] = []

        try:
            _bootstrap.resolve(
                config_path=cfg.backend.sd_scripts_path,
                config_python=cfg.backend.python_executable,
            )
        except _bootstrap.BootstrapError as e:
            issues.append(ValidationIssue(Severity.error, "backend.sd_scripts_path", str(e)))

        try:
            compile_config(cfg, workspace=Path("/"))
        except CompilationError as e:
            issues.append(ValidationIssue(Severity.error, "recipe", str(e)))

        if not cfg.base_model.checkpoint.exists():
            issues.append(
                ValidationIssue(
                    Severity.warning,
                    "base_model.checkpoint",
                    f"checkpoint file does not exist: {cfg.base_model.checkpoint}",
                )
            )
        if not cfg.dataset.source.exists():
            issues.append(
                ValidationIssue(
                    Severity.warning,
                    "dataset.source",
                    f"dataset directory does not exist: {cfg.dataset.source}",
                )
            )

        return issues

    def estimate_vram(self, cfg: TrainingConfig) -> VRAMEstimate:
        """Coarse VRAM estimate. Refine with empirical data later.

        The per-arch tables and the formula live in
        ``lorahub.core.backends._common.vram`` so the kohya and
        diffusion-pipe backends stay in lockstep.
        """
        return _shared_estimate_vram(
            cfg.base_model.arch,
            precision=cfg.precision,
            batch_size=cfg.schedule.batch_size,
            network_rank=cfg.network.rank,
            gradient_checkpointing=cfg.gradient_checkpointing,
        )

    def launch(
        self,
        cfg: TrainingConfig,
        workspace: Path,
        on_event: Callable[[TrainingEvent], None],
        *,
        extra_argv: list[str] | None = None,
        env: dict[str, str] | None = None,
    ) -> TrainingHandle:
        bootstrap_env = _bootstrap.resolve(
            config_path=cfg.backend.sd_scripts_path,
            config_python=cfg.backend.python_executable,
        )
        workspace = workspace.resolve()
        script_name, argv, files, compile_env = compile_config(cfg, workspace)
        if extra_argv:
            argv = [*argv, *extra_argv]
        workspace.mkdir(parents=True, exist_ok=True)
        for path, content in files.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
        script = bootstrap_env.script(script_name)

        # Merge env: caller env wins, then compiler env (FA3/FA4 override)
        # is layered underneath so users can still strip it via env={}.
        merged_env: dict[str, str] = {**compile_env, **(env or {})}

        # If the compiler asked for a FA3/FA4 attention override, stage a
        # ``sitecustomize.py`` shim under the workspace and prepend it to
        # PYTHONPATH so the spawned interpreter loads it before kohya. The
        # shim simply imports our patch module and calls ``apply()``.
        if compile_env.get(_attn_patch.OVERRIDE_ENV):
            shim_dir = _stage_attn_patch(workspace)
            existing = merged_env.get("PYTHONPATH") or os.environ.get("PYTHONPATH", "")
            joined = (
                f"{shim_dir}{os.pathsep}{existing}" if existing else str(shim_dir)
            )
            merged_env["PYTHONPATH"] = joined

        job_id = str(ulid.new())
        runner = KohyaRunner(
            python=bootstrap_env.python_executable,
            script=script,
            argv=argv,
            workspace=workspace,
            on_event=on_event,
            job_id=job_id,
            env=merged_env or None,
        )
        runner.start()

        return TrainingHandle(
            job_id=job_id,
            pid=runner.pid,
            _stop_fn=lambda graceful: runner.stop(graceful=graceful),
            _wait_fn=lambda timeout: runner.wait(timeout=timeout).returncode,
        )
