"""LoraHub: an open-source LoRA training workbench for diffusion models."""

# `_version.py` is generated by hatch-vcs when the package is built or
# installed editable. In a fresh checkout that hasn't been installed
# yet (e.g. running tests directly off the source tree without
# `pip install -e .` first) the file may be absent — fall back to a
# dev marker rather than crashing the import.
try:
    from lorahub._version import __version__
except ImportError:  # pragma: no cover — only hits in pre-install runs
    __version__ = "0.0.0+unknown"

__all__ = ["__version__"]
